# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9ebcbe7d52eca7677231bc2b4d5098588218ea93184b52ed17cb8cef2286085ceaf424c99b45597dc18be3017bfb32d26f64b3c55ea939f75dd7b7bea4ddb13

test:
  secret_key_base: 905e0e0e7aa8bd2f1f158be0c74df7e7d10c26416146216903e4123f8b0acbd9311883cabfdf64beb448ba0877b5e39ab8e97b0634ce353dad505de40fe99c83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
